version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo $HELLO
workflows:
  version: 2
  build-1:
    jobs:
      - build:
          context: hello_world
  build-2:
    jobs:
      - build:
          context: hello-world
  build-3:
    jobs:
      - build:
          context: TEST
